data:
  dataset_name: LIDC-IDRI
  data_preprocessing_protocol_number: 1
  dataloader:
    dataset_name: LIDC-IDRI
    data_preprocessing_protocol_number: 1
    data_augmentation:
      apply: false
      augmented_to_original_data_ratio: 2
      parameters:
        number_of_augmentations: 3
        random_rotation_degrees: 10
        random_translation_fraction: 0.1
        random_brightness_intensity_factor: 0.3
        random_contrast_intensity_factor: 0.3
        random_gaussian_blur:
          kernel_size:
          - 3
          - 3
          sigma:
          - 0.1
          - 1.0
        random_gaussian_noise_variance: 0.001
        random_elastic_alpha: 10.0
        random_elastic_sigma: 5.0
    image_numpy_arrays_dir_path: C:\Users\janto\OneDrive\Ambiente de Trabalho\Dissertação\Masters-Thesis\data/preprocessed_data/protocol_1/image_numpy_arrays
    input_data_size:
    - 1
    - 32
    - 32
    include_labels:
      lnva:
        mean: false
        std: false
      lnm:
        mean: true
        std: false
    lnva_names:
    - subtlety
    - internal_structure
    - calcification
    - sphericity
    - margin
    - lobulation
    - spiculation
    - texture
    mask_numpy_arrays_dir_path: C:\Users\janto\OneDrive\Ambiente de Trabalho\Dissertação\Masters-Thesis\data/preprocessed_data/protocol_1/mask_numpy_arrays
    number_of_lnm_scores: 5
    number_of_k_folds: 5
    seed_value: 1
    score_counts:
      subtlety: 5
      internal_structure: 4
      calcification: 6
      sphericity: 5
      margin: 5
      lobulation: 5
      spiculation: 5
      texture: 5
    test_fraction_of_entire_dataset: 0.2
    torch_dataloader_kwargs:
      batch_size: 64
      num_workers: 0
    use_mode_for_internal_structure_and_calcification: false
    validation_fraction_of_train_set: 0.1
  metadataframe:
    dataset_name: LIDC-IDRI
    data_preprocessing_protocol_number: 1
    lnva:
      names:
      - subtlety
      - internal_structure
      - calcification
      - sphericity
      - margin
      - lobulation
      - spiculation
      - texture
      score_counts:
        subtlety: 5
        internal_structure: 4
        calcification: 6
        sphericity: 5
        margin: 5
        lobulation: 5
        spiculation: 5
        texture: 5
      quantity: 8
    use_mode_for_internal_structure_and_calcification: false
experiment_execution:
  ids:
    experiment_id: 25
    experiment_version_id: 8
  info:
    who: Joao Malva
    what: Exp 17 - Continuation rest of 64 batch_size
  paths:
    experiment_dir_path: C:\Users\janto\OneDrive\Ambiente de Trabalho\Dissertação\Masters-Thesis/experiment_results/experiment_25
    experiment_version_dir_path: C:\Users\janto\OneDrive\Ambiente de Trabalho\Dissertação\Masters-Thesis/experiment_results/experiment_25/version_8
    preprocessed_data_dir_path: C:\Users\janto\OneDrive\Ambiente de Trabalho\Dissertação\Masters-Thesis\data/preprocessed_data
    python_project_dir_path: C:\Users\janto\OneDrive\Ambiente de Trabalho\Dissertação\Masters-Thesis
hyperparameter_grid_based_execution:
  apply: true
  hyperparameter_combination:
    index: 8
    used:
      seed_value: 1
      model.pytorch_lightning_model.hyperparameters.optimiser.kwargs.lr: 1.0e-05
      data.dataloader.torch_dataloader_kwargs.batch_size: 64
      model.pytorch_lightning_model.hyperparameters.svm_config.extractors:
      - fof
      model.pytorch_lightning_model.hyperparameters.resnet_config.default_layer: layer4
  hyperparameter_grid:
    seed_value:
    - 1
    model.pytorch_lightning_model.hyperparameters.optimiser.kwargs.lr:
    - 1.0e-05
    data.dataloader.torch_dataloader_kwargs.batch_size:
    - 64
    model.pytorch_lightning_model.hyperparameters.svm_config.extractors:
    - - lbp
    - - fof
    - - haralick
    model.pytorch_lightning_model.hyperparameters.resnet_config.default_layer:
    - layer1
    - layer2
    - layer3
    - layer4
model:
  model_id: ResNetFusionModel
  model_name: ResNetFusionModel
  model_pipeline:
    model_id: ResNetFusionModel
    model_name: ResNetFusionModel
    callbacks:
      model_checkpoints:
      - monitor: val_auroc
        filename: mod=ResNetFusionModel-exp=X-ver=Y-dtf=Z-{epoch}-var={val_auroc:.3f}
        mode: max
        save_top_k: 1
      - monitor: val_loss
        filename: mod=ResNetFusionModel-exp=X-ver=Y-dtf=Z-{epoch}-var={val_loss:.3f}
        mode: min
        save_top_k: 1
      - filename: mod=ResNetFusionModel-exp=X-ver=Y-dtf=Z-{epoch}-var=last_epoch
      model_early_stoppings:
      - monitor: val_auroc
        patience: 25
        mode: max
        verbose: true
    enable_logging: true
    enable_model_early_stopping: true
    finalization:
      delete_model_checkpoints: true
      save_used_data_file_names: true
    pytorch_lightning_model:
      model_id: ResNetFusionModel
      model_name: ResNetFusionModel
      hyperparameters:
        device: cuda
        optimiser:
          type: Adam
          kwargs:
            lr: 1.0e-05
        number_of_classes: 2
        effnet_config:
          architecture: b0
          criterion:
            apply_weights: true
            device: cuda
            metadataframe:
              dataset_name: LIDC-IDRI
              data_preprocessing_protocol_number: 1
              lnva:
                names:
                - subtlety
                - internal_structure
                - calcification
                - sphericity
                - margin
                - lobulation
                - spiculation
                - texture
                score_counts:
                  subtlety: 5
                  internal_structure: 4
                  calcification: 6
                  sphericity: 5
                  margin: 5
                  lobulation: 5
                  spiculation: 5
                  texture: 5
                quantity: 8
              use_mode_for_internal_structure_and_calcification: false
          optimiser:
            type: Adam
            kwargs:
              lr: 1.0e-05
        svm_config:
          criterion: hinge
          optimiser:
            type: Adam
            kwargs:
              lr: 1.0e-05
          extractors:
          - fof
        resnet_config:
          architecture: 18
          default_layer: layer4
          criterion:
            apply_weights: true
            device: cuda
            metadataframe:
              dataset_name: LIDC-IDRI
              data_preprocessing_protocol_number: 1
              lnva:
                names:
                - subtlety
                - internal_structure
                - calcification
                - sphericity
                - margin
                - lobulation
                - spiculation
                - texture
                score_counts:
                  subtlety: 5
                  internal_structure: 4
                  calcification: 6
                  sphericity: 5
                  margin: 5
                  lobulation: 5
                  spiculation: 5
                  texture: 5
                quantity: 8
              use_mode_for_internal_structure_and_calcification: false
          optimiser:
            type: Adam
            kwargs:
              lr: 1.0e-05
          extractors:
          - name: fft_magnitude
    pytorch_lightning_trainer_kwargs:
      accelerator: gpu
      enable_checkpointing: true
      enable_model_summary: false
      enable_progress_bar: false
      log_every_n_steps: 1
      min_epochs: 0
      max_epochs: 100
  pytorch_lightning_model:
    model_id: ResNetFusionModel
    model_name: ResNetFusionModel
    hyperparameters:
      device: cuda
      optimiser:
        type: Adam
        kwargs:
          lr: 1.0e-05
      number_of_classes: 2
      effnet_config:
        architecture: b0
        criterion:
          apply_weights: true
          device: cuda
          metadataframe:
            dataset_name: LIDC-IDRI
            data_preprocessing_protocol_number: 1
            lnva:
              names:
              - subtlety
              - internal_structure
              - calcification
              - sphericity
              - margin
              - lobulation
              - spiculation
              - texture
              score_counts:
                subtlety: 5
                internal_structure: 4
                calcification: 6
                sphericity: 5
                margin: 5
                lobulation: 5
                spiculation: 5
                texture: 5
              quantity: 8
            use_mode_for_internal_structure_and_calcification: false
        optimiser:
          type: Adam
          kwargs:
            lr: 1.0e-05
      svm_config:
        criterion: hinge
        optimiser:
          type: Adam
          kwargs:
            lr: 1.0e-05
        extractors:
        - fof
      resnet_config:
        architecture: 18
        default_layer: layer4
        criterion:
          apply_weights: true
          device: cuda
          metadataframe:
            dataset_name: LIDC-IDRI
            data_preprocessing_protocol_number: 1
            lnva:
              names:
              - subtlety
              - internal_structure
              - calcification
              - sphericity
              - margin
              - lobulation
              - spiculation
              - texture
              score_counts:
                subtlety: 5
                internal_structure: 4
                calcification: 6
                sphericity: 5
                margin: 5
                lobulation: 5
                spiculation: 5
                texture: 5
              quantity: 8
            use_mode_for_internal_structure_and_calcification: false
        optimiser:
          type: Adam
          kwargs:
            lr: 1.0e-05
        extractors:
        - name: fft_magnitude
results_analysis:
  model_test_performance_metrics_dataframe:
    monitored_variables:
    - val_auroc
    - val_loss
    - last_epoch
  model_training_performance_metrics_figure:
    maximum_number_of_epochs: 100
seed_value: 1
