name: preprocessed_data_loading_jn_venv
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - python=3.11.5
  - pip=23.2.1
  - pip:
      - albumentations==1.4.18
      - hydra-core==1.3.2
      - ipykernel==6.7.0
      - torch==2.1.1
      - torchvision==0.16.1
      - numpy==1.25.2
      - omegaconf==2.3.0
      - pandas==2.1.0rc0
      - scikit-learn==1.6.1