defaults:
  - data/preprocessed/loader: lidc_idri_preprocessed_data_loader
  - data/raw/loader: lidc_idri_raw_data_loader
  - metadata/preprocessed: lidc_idri_preprocessed_metadata
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled
  - _self_
hydra:
  output_subdir: null
  run:
    dir: .

data_and_metadata_storage_source: internal