model_id: ${..model_id}
model_name: ${..model_name}
hyperparameters:
  device: cuda
  number_of_classes: 2
  # Couldn't transport the value for execution so I setted it to 1024 in the linear_svm_model.py
  input_dim: 1024
  optimiser:
    type: Adam
    kwargs:
      lr: 0.00001
  criterion:
    apply_weights: True
    device: ${..device}
    metadataframe: ${.....data.metadataframe}
  model:
    number_of_classes: 2
