model_id: ${..model_id}
model_name: ${..model_name}
hyperparameters:
  input_dim: 1024
  device: cuda
  optimiser:
    type: Adam
    kwargs:
      lr: 0.00001
  criterion: hinge
  #TODO: GRID of the following hyperparameters for LBP extraction
  # self.P = P
  # self.R = R
  # self.method = method