# filepath: /nas-ctm01/homes/jmalva/Masters-Thesis/config_files/model/pytorch_lightning_model/luna25_pytorch_lightning_effnet_svm.yaml
model_id: ${..model_id}
model_name: ${..model_name}
hyperparameters:
  device: cuda

  optimiser:
    type: Adam #Maybe also try AdamW
    kwargs:
      lr: 0.00001
      #weight_decay: 0.0001 #does this help?

  number_of_classes: 2
  
  # EfficientNet parameters
  effnet_config:
    architecture: b2
    criterion:
      apply_weights: True
      device: ${...device}
      metadataframe: ${......data.metadataframe}
    optimiser: ${..optimiser}

  # SVM parameters
  svm_config:
    input_dim: 2418 # number of features being tested
    #input_dim: 1024 # number of LBP features per image
    criterion: hinge
    optimiser: ${..optimiser}
    #TODO: GRID of the following hyperparameters for LBP extraction (maybe not needed)
    # P: <value>
    # R: <value>
     # method: <value>
    extractors:
      - fft_magnitude
      - fft_phase
      - gabor
      - hog
      - entropy
      - mean
      - std
      - MeshSurface
      - Perimeter
      - Sphericity
      - glcm
      - lbp

  # ResNet parameters
  resnet_config:
    architecture: 18         # Options: 18, 34, 50, 101, 152, etc.
    default_layer: layer3  # Options: layer1, layer2, layer3, layer4
    criterion:
      apply_weights: True
      device: ${...device}
      metadataframe: ${......data.metadataframe}
    optimiser: ${..optimiser}
    extractors:
      - name: fft_magnitude
        layer: layer1 # if none specified, it will use the default_layer
      - name: fft_phase
        layer: layer2 # if none specified, it will use the default_layer
      - name: gabor
        layer: layer3 # if none specified, it will use the default_layer
      - name: hog
        layer: layer4 # if none specified, it will use the default_layer
      - name: entropy
        layer: layer1
      - name: mean
        layer: layer2
      - name: std
        layer: layer3
      - name: MeshSurface
        layer: layer4
      - name: Perimeter
        layer: layer1
      - name: Sphericity
        layer: layer2
      - name: glcm
        layer: layer3
      - name: lbp
        layer: layer4